config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'cards' => 'cards#index'
  root 'cards#index'

  get 'cards/:id', to: 'cards#show', id: /\d+/

  get 'about' => 'about#index'

  get 'artists/:id', to: 'artists#show', id: /\d+/ 

  get 'expansions/:id', to: 'expansions#show', id: /\d+/
 
  get 'search' => 'search#index'
  get 'search' => 'search#show'

  get 'advancedsearch' => 'advancedsearch#index'

  get 'random' => 'cards#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :cardartists
	has_many :cards, through: :cardartists

	validates :artist_name, presence: true, uniqueness: true
end

app/models/card.rb
class Card < ApplicationRecord
	has_many :images
	has_many :cardexpansions
	has_many :expansions, through: :cardexpansions
	has_many :cardartists
	has_many :artists, through: :cardartists
	has_many :cardtypes
	has_many :types, through: :cardtypes

	validates :name, presence: true, uniqueness: true
	validates :artist, presence: true
	validates :expansion, presence: true
	validates :image, presence: true
end

app/models/cardartist.rb
class Cardartist < ApplicationRecord
  belongs_to :card
  belongs_to :artist
end

app/models/cardexpansion.rb
class Cardexpansion < ApplicationRecord
  belongs_to :card
  belongs_to :expansion
end

app/models/cardtype.rb
class Cardtype < ApplicationRecord
  belongs_to :card
  belongs_to :type
end

app/models/expansion.rb
class Expansion < ApplicationRecord
	has_many :cardexpansions
	has_many :cards, through: :cardexpansions

	validates :expansion_name, presence: true, uniqueness: true
	validates :short_code, presence: true, uniqueness: true
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :cards

	validates :image_name, presence: true
	validates :path, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
	has_many :cardtypes
	has_many :cards, through: :cardtypes

	validates :type_name, presence: true, uniqueness: true
	validates :category, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index
		@cards = Card.page(params[:page]).per(50)
	end

	def show
		@card = Card.find(params[:id])
	end
end

app/controllers/random_controller.rb
class RandomController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def index
		@cards = Card.where("name LIKE ?", "%#{params[:name]}%")
	end

	def show
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/expansions_helper.rb
module ExpansionsHelper
end

app/helpers/random_helper.rb
module RandomHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MTG Finder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>MTG Finder</h1>
      <ul>
        <li><%= link_to "Home Page", cards_path %></li>
        <li><%= link_to "Search by Name", search_path %></li>
        <li><%= link_to "Advanced Search", advancedsearch_path %></li>
        <li><%= link_to "Random Card", controller: "cards", action: "show", id: rand(Card.count) %></li>
        <li><%= link_to "About Page", about_path %></li>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>